services:
  postgres:
    image: postgres:14
    restart: always
    user: "999:999"  # Ensuring the container runs with user postgres
    environment:
      POSTGRES_DB: authentication_example
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres-data:
    driver: local
